name: conductor
services:
  conduktor-console:
    depends_on:
      postgresql:
        condition: service_healthy
        required: true
    environment:
      CDK_DATABASE_URL: postgresql://conduktor:change_me@postgresql:5432/conduktor-console
      CDK_ORGANIZATION_NAME: getting-started
    image: conduktor/conduktor-console:1.43.1
    networks:
      default: null
    ports:
      - mode: ingress
        target: 8080
        published: "8080"
        protocol: tcp
    volumes:
      - type: volume
        source: conduktor_data
        target: /var/conduktor
        volume: {}
  postgresql:
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: conduktor-console
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_PASSWORD: change_me
      POSTGRES_USER: conduktor
    hostname: postgresql
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U conduktor -d conduktor-console
      timeout: 5s
      interval: 10s
      retries: 5
    image: postgres:14
    networks:
      default: null
    volumes:
      - type: volume
        source: pg_data
        target: /var/lib/postgresql/data
        volume: {}
networks:
  default:
    name: conductor_default
volumes:
  conduktor_data:
    name: conductor_conduktor_data
  pg_data:
    name: conductor_pg_data
